<?php

namespace App\Controller\Admin\DH;

use App\Entity\DH\DhCarriere;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class DhCarriereCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return DhCarriere::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInPlural('Carrière')
            ->setEntityLabelInSingular('Carrières')

            ->setPageTitle('index', 'Dark Heresy - Carrières')
            ;// TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')
                ->hideOnForm(),
            TextField::new('name'),
            TextareaField::new('description')->hideOnIndex(),
            TextField::new('argentOnCreate')->hideOnIndex(),
        ];
    }
}
