<?php

namespace App\Controller\Admin\DH;

use App\Entity\DH\DhCompetence;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class DhCompetenceCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return DhCompetence::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInPlural('Compétence')
            ->setEntityLabelInSingular('Compétences')

            ->setPageTitle('index', 'Dark Heresy - Carrières')
            ;// TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')
                ->hideOnForm(),
            TextField::new('name'),
            TextField::new('type'),
            TextField::new('caracteristique'),
            BooleanField::new('is_group')->hideOnIndex(),
            TextField::new('groupName')->hideOnIndex(),
            TextField::new('registre'),
            TextareaField::new('description')->hideOnIndex(),
            TextareaField::new('capacite')->hideOnIndex(),
        ];
    }
}
