<?php

namespace App\Controller\Admin\DH;

use App\Entity\DH\DhTalent;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class DhTalentCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return DhTalent::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInPlural('Talent')
            ->setEntityLabelInSingular('Talents')

            ->setPageTitle('index', 'Dark Heresy - Talents')
            ->setPaginatorPageSize(100)
            ;// TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')
                ->hideOnForm(),
            TextField::new('name'),
            TextField::new('requis'),
            TextareaField::new('description')->hideOnIndex(),
        ];
    }
}
