<?php

namespace App\Controller\Admin\DH;

use App\Entity\DH\DhMondeNatal;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class MondeNatalCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return DhMondeNatal::class;
    }


    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInPlural('Monde natal')
            ->setEntityLabelInSingular('Mondes natals')

        ->setPageTitle('index', 'Dark Heresy - Monde Natal')
            ;// TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')
                ->hideOnForm(),
            TextField::new('name'),
            TextareaField::new('description'),
            IntegerField::new('min'),
            IntegerField::new('max'),
        ];
    }

}
